### ISSUE TITLE
GetAffordableRecipes query is returning recipes with price greater than given max

### ISSUE THREAD

**Issue by laurel-thomson** [dkhwang118/CIS560_F18-Project-RecipeManager#71]

**Comment by dkhwang118** [comment]
I think I fixed it. Pushed to master after testing on the DB without the generated data. Will test further later.

**Comment by laurel-thomson** [comment]
I'm still having issues.  Whenever I try to find all recipes with price less than 0 dollars, I'm getting recipes with a positive price.

**Comment by laurel-thomson** [comment]
Oh wait, I forgot that we were subtracting away the value of the items that the user already owns in their pantry when calculating this.  Nevermind!  Seems to be working fine.
